/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.projeto_integrador;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author 26.00755-9
 */
public class circular extends javax.swing.JPanel {

    private int progress = 0; // Porcentagem de 0 a 100

    /**
     * Creates new form circular
     */
    public circular() {
        initComponents();
        setOpaque(false); // Mantém o fundo transparente para o design do quiz
    }

    // Método para atualizar o progresso dinamicamente
    public void setProgress(int progress) {
        if (progress < 0) this.progress = 0;
        else if (progress > 100) this.progress = 100;
        else this.progress = progress;
        
        repaint(); // Força o componente a se redesenhar na tela
    }

    public int getProgress() {
        return progress;
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;

        // Ativa o anti-aliasing para deixar as bordas suaves
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        int width = getWidth();
        int height = getHeight();
        int size = Math.min(width, height) - 20; // Tamanho do círculo com margem
        int x = (width - size) / 2;
        int y = (height - size) / 2;

        int strokeWidth = 12; // Espessura da linha do gráfico

        // 1. Desenhar o círculo de fundo (Cinza claro)
        g2d.setColor(new Color(230, 230, 230));
        g2d.setStroke(new BasicStroke(strokeWidth, BasicStroke.CAP_ROUND, BasicStroke.JOIN_ROUND));
        g2d.drawOval(x, y, size, size);

        // 2. Desenhar o arco de progresso (Azul Escuro da imagem)
        g2d.setColor(new Color(0, 74, 173)); 
        
        int startAngle = 90; // Começa no topo (12h)
        int angle = (int) -(progress * 3.6); // Converte porcentagem para graus (sentido horário)
        
        g2d.drawArc(x, y, size, size, startAngle, angle);

        // 3. Desenhar o texto centralizado (Ex: "30%")
        String text = progress + "%";
        g2d.setColor(Color.BLACK);
        g2d.setFont(new Font("Arial", Font.BOLD, 32)); 

        // Cálculos para centralizar o texto
        int textWidth = g2d.getFontMetrics().stringWidth(text);
        int textHeight = g2d.getFontMetrics().getAscent();
        int textX = (width - textWidth) / 2;
        int textY = (height + textHeight) / 2 - 5; 

        g2d.drawString(text, textX, textY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1058, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
