/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_integrador;

/**
 *
 * @author 26.00755-9
 */
public class Dificuldade extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dificuldade.class.getName());

    /**
     * Creates new form Dificuldade
     */
    public Dificuldade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnfacil = new javax.swing.JButton();
        btndificil = new javax.swing.JButton();
        JLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnfacil.setBorderPainted(false);
        btnfacil.setContentAreaFilled(false);
        btnfacil.setFocusPainted(false);
        btnfacil.addActionListener(this::btnfacilActionPerformed);
        getContentPane().add(btnfacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 190, 230));

        btndificil.setText("jButton1");
        btndificil.setBorderPainted(false);
        btndificil.setContentAreaFilled(false);
        btndificil.setFocusPainted(false);
        btndificil.addActionListener(this::btndificilActionPerformed);
        getContentPane().add(btndificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 200, 240));

        JLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b3900ff2-e7b3-4270-abac-58e76641.png"))); // NOI18N
        JLabel1.setText("jLabel1");
        getContentPane().add(JLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnfacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfacilActionPerformed
        TelaQuiz jogo = new TelaQuiz("Fácil");
        jogo.setVisible(true);
    this.dispose(); // Fecha a tela de dificuldade
    }//GEN-LAST:event_btnfacilActionPerformed

    private void btndificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndificilActionPerformed
        TelaQuiz jogo = new TelaQuiz("Difícil");
        jogo.setVisible(true);
    this.dispose(); // Fecha a tela de dificuldade        // TODO add your handling code here:
    }//GEN-LAST:event_btndificilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dificuldade().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel1;
    private javax.swing.JButton btndificil;
    private javax.swing.JButton btnfacil;
    // End of variables declaration//GEN-END:variables
}
