
 /
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 /
 
 
package com.mycompany.projeto_integrador;
 
 import javax.swing.JOptionPane; 
/**
 *
 * @author 26.00755-9
 */
public class TelaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnlogar = new java.awt.Button();
        txtlogin = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        txtsenha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnregistrar = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnlogar.setLabel("button1");
        btnlogar.addActionListener(this::btnlogarActionPerformed);
        getContentPane().add(btnlogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 280, 50));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        txtlogin.setViewportView(jTextArea2);

        getContentPane().add(txtlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 240, 30));

        txtsenha.setText("jPasswordField1");
        getContentPane().add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 200, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/592e7107-7100-4b61-82e7-df407124.png"))); // NOI18N
        jLabel4.setText("jLabel2");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 1110, 700));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));

        btnregistrar.setLabel("button1");
        btnregistrar.addActionListener(this::btnregistrarActionPerformed);
        getContentPane().add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, 280, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogarActionPerformed
    String email = txtlogin.getText();
    String senha = txtsenha.getText();

    boolean usuarioExiste = Conexao.validarLogin(email, senha);

    if(usuarioExiste){

        JOptionPane.showMessageDialog(null, "Login realizado!");

    // ABRE A TELA PRINCIPAL
         TelaInicio tela = new TelaInicio();

            tela.setVisible(true);

               dispose();

    }else{

        JOptionPane.showMessageDialog(null,
            "Usuário não encontrado!\nFaça o cadastro.");

    // ABRE TELA DE REGISTRO
        TelaRegistrar tela = new TelaRegistrar();

            tela.setVisible(true);

                dispose();
}    // TODO add your handling code here:
    }//GEN-LAST:event_btnlogarActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
    TelaRegistrar tela = new TelaRegistrar();

    tela.setVisible(true);

    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnregistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnlogar;
    private java.awt.Button btnregistrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JScrollPane txtlogin;
    private javax.swing.JPasswordField txtsenha;
    // End of variables declaration//GEN-END:variables
}
