/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_integrador;

/**
 *
 * @author User
 */
public class TelaQuiz extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaQuiz.class.getName());

    private String[][] perguntasMapeadas = {
        {"Qual das alternativas representa uma mudança química?", "Gelo derretendo em água.", "Água evaporando em vapor.", "Queima de papel.", "Sal se dissolvendo em água.", "C"},
        {"Qual o símbolo químico da água?", "H2O", "CO2", "O2", "NaCl", "A"},
        {"Qual desses elementos é um gás nobre?", "Oxigênio", "Hélio", "Ferro", "Sódio", "B"}
    };

    private int indicePergunta = 0;
    private int quantidadeAcertos = 0;
    private int quantidadeErros = 0;
    /**
     * Creates new form TelaQuiz
     */
    public TelaQuiz() {
        initComponents();
        atualizarPainelQuiz();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbOpcaoA = new javax.swing.JRadioButton();
        rbOpcaoB = new javax.swing.JRadioButton();
        rbOpcaoC = new javax.swing.JRadioButton();
        rbOpcaoD = new javax.swing.JRadioButton();
        btnProxima = new javax.swing.JButton();
        lblPergunta = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(rbOpcaoA);
        rbOpcaoA.setOpaque(true);
        rbOpcaoA.addActionListener(this::rbOpcaoAActionPerformed);
        getContentPane().add(rbOpcaoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 400, 60));

        buttonGroup1.add(rbOpcaoB);
        rbOpcaoB.setOpaque(true);
        rbOpcaoB.addActionListener(this::rbOpcaoBActionPerformed);
        getContentPane().add(rbOpcaoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 630, 70));

        buttonGroup1.add(rbOpcaoC);
        rbOpcaoC.setOpaque(true);
        getContentPane().add(rbOpcaoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 630, 70));

        buttonGroup1.add(rbOpcaoD);
        rbOpcaoD.setOpaque(true);
        rbOpcaoD.addActionListener(this::rbOpcaoDActionPerformed);
        getContentPane().add(rbOpcaoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 550, 630, 70));

        btnProxima.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnProxima.setForeground(new java.awt.Color(255, 255, 255));
        btnProxima.setBorderPainted(false);
        btnProxima.setContentAreaFilled(false);
        btnProxima.addActionListener(this::btnProximaActionPerformed);
        getContentPane().add(btnProxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 650, 270, 70));

        lblPergunta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(lblPergunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 660, 40));

        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVoltar.setBorderPainted(false);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ultimo_quiz.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1600, 900));
        jLabel1.setMinimumSize(new java.awt.Dimension(1600, 900));
        jLabel1.setPreferredSize(new java.awt.Dimension(1600, 900));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, -30, 1600, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbOpcaoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOpcaoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOpcaoAActionPerformed

    private void btnProximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximaActionPerformed
String alternativaEscolhida = "";
        
        if (rbOpcaoA.isSelected()) alternativaEscolhida = "A";
        else if (rbOpcaoB.isSelected()) alternativaEscolhida = "B";
        else if (rbOpcaoC.isSelected()) alternativaEscolhida = "C";
        else if (rbOpcaoD.isSelected()) alternativaEscolhida = "D";
        
        if (alternativaEscolhida.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione uma das alternativas!");
            return; 
        }
        
        if (alternativaEscolhida.equals(perguntasMapeadas[indicePergunta][5])) {
            quantidadeAcertos++;
        } else {
            quantidadeErros++;
        }
        
        indicePergunta++;
        atualizarPainelQuiz();    }//GEN-LAST:event_btnProximaActionPerformed

    private void rbOpcaoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOpcaoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOpcaoBActionPerformed

    private void rbOpcaoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOpcaoDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOpcaoDActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
TelaLogin telaAnterior = new TelaLogin();
telaAnterior.setVisible(true);

this.dispose();    }//GEN-LAST:event_btnVoltarActionPerformed

    private void atualizarPainelQuiz() {
        if (indicePergunta < perguntasMapeadas.length) {
            // Alimenta os componentes com os dados da matriz
            lblPergunta.setText(perguntasMapeadas[indicePergunta][0]);
            rbOpcaoA.setText(perguntasMapeadas[indicePergunta][1]);
            rbOpcaoB.setText(perguntasMapeadas[indicePergunta][2]);
            rbOpcaoC.setText(perguntasMapeadas[indicePergunta][3]);
            rbOpcaoD.setText(perguntasMapeadas[indicePergunta][4]);
            
            buttonGroup1.clearSelection(); 
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Você concluiu todas as perguntas deste bloco!");
            btnProxima.setEnabled(false); 
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProxima;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblPergunta;
    private javax.swing.JRadioButton rbOpcaoA;
    private javax.swing.JRadioButton rbOpcaoB;
    private javax.swing.JRadioButton rbOpcaoC;
    private javax.swing.JRadioButton rbOpcaoD;
    // End of variables declaration//GEN-END:variables
}
