/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.projeto_integrador;

/**
 *
 * @author 26.00755-9
 */
public class TelaFinalQuiz extends javax.swing.JFrame {

    /**
     * Creates new form TelaFinalQuiz
     */
    public TelaFinalQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnverperfil = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnverperfil.setText(" ");
        btnverperfil.setBorderPainted(false);
        btnverperfil.setContentAreaFilled(false);
        btnverperfil.setFocusPainted(false);
        btnverperfil.addActionListener(this::btnverperfilActionPerformed);
        getContentPane().add(btnverperfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 290, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mama (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 606));
    }// </editor-fold>//GEN-END:initComponents

    private void btnverperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverperfilActionPerformed
        TelaPerfil perfil = new TelaPerfil();
    perfil.setVisible(true);

    this.dispose();  
    }//GEN-LAST:event_btnverperfilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnverperfil;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

 
}
